module.exports = {
    MAX_POS_PLANE_TOP : 60,
    MAX_POS_PLANE_LEFT : 120,
    MAX_POS_PLANE_RIGHT : 1140,
    SPEED_ROT_RUDDER : 2.5,
    MAX_ROT_RUDDER_TOP :70,
    MAX_ROT_RUDDER_BOTTOM : 10,
    PADDING_MOUSE_POS_RUDDER  : 20,
    SPEED_PLANE_RIGHT : 8,
    SPEED_PLANE_TOP : 8,
    PLANE_INIT_POS_X : 200,
    PLANE_INIT_POS_Y : 100,
    ROCKET_SPEED : 10
}

